### ISSUE TITLE
Migrate to fjåge 1.7 parameter framework

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage-sentuator#2]
Moving to fjåge 1.7 parameter framework will improve compatibility with other projects that use fjåge.

**Comment by notthetup** [comment]
This should be fixed by https://github.com/org-arl/fjage-sentuator/commit/2cf32c1d06f359e4fa22f4e5e1ac042ad9d6dd65 right?

**Comment by mchitre** [comment]
Yup
