### ISSUE TITLE
Have a mechanism to capture a timestamp for each Measurement?

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage-sentuator#3]
It may be useful to have a timestamp associated with each Measurement. It could be an optional field.

**Comment by mchitre** [comment]
Isn't this exactly that?

https://github.com/org-arl/fjage-sentuator/blob/43ca801256585ed37dcbf1cbb619a42c27a2f0f4/src/main/groovy/org/arl/fjage/sentuator/Measurement.groovy#L14

**Comment by notthetup** [comment]
Whoops! I missed that.!
