### ISSUE TITLE
GenericMeasurement can implement the Map interface

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage-sentuator#5]
GenericMeasurement supports the `set (String, Object(` and `get(String)` Map-like methods. If it also implements the Map interface then it can be used in the way shown in the example even in statically type-checked code.

```
> mysen.measure()
GenericMeasurement[type:Demo Sentuator x:1.0283573 m]

> mysen.measure().x
1.8090699

> mysen.measure().x
1.395348
```

**Comment by notthetup** [comment]
I looked into this more. It's strange. The Map interface is Java defines..

`get(Object key)` and `put(K key, V value)` which isn't the same as what `GenericMeasurement ` implements. So still not sure why this works without static type checking.

**Comment by mchitre** [comment]
Groovy uses a [meta object protocol (MOP)](https://groovy-lang.org/metaprogramming.html) to handle missing methods or properties, allowing code to inject these dynamically at run-time.

Example:
```groovy
groovy:000> class X {
groovy:001>   def get(String s) {
groovy:002>     return 7
groovy:003>   }
groovy:004> }
===> true
groovy:000> x = new X()
===> X@5ddea849
groovy:000> x.a
===> 7
```

The way this code works is that the `x.a` calls `getProperty()` on `x` with `a` as a parameter. The default implementation of the `getProperty()` method tries to return value of `a` through a variety of methods: field `a` defined in the class, attribute available via `getAttribute()`, map value available via a `get()` method, field or attribute defined via the meta-class registry (used typically to insert methods on POJOs or on Groovy classes that are defined by 3rd party packages), and eventually delegates to a `propertyMissing()` method, which throws a `MissingMethodException` exception. In our example above, the `get('a')` returns 7, and so `x.a` returns 7.

The MOP is bypassed when [`@CompileStatic`](https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html) is used, as the compiler needs to determine `x.a` at compile time. The compiler checks to see if there is a field `x`, or a Java-bean property defined by `getX()`, and if so statically uses that to resolve `x.a`. If that fails, compiler checks to see if class `X` is a `Map` and then uses `get()` to provide the value of `a`.

Example:

```groovy
class X {
  def get(s) {
    return 7
  }
}

class Y {
  def f() {
    def x = new X()
    return x.a
  }
}

y = new Y()
println y.f()
```
runs fine, and prints `7`.

`t.groovy`:
```groovy
class X {
  def get(s) {
    return 7
  }
}

@groovy.transform.CompileStatic
class Y {
  def f() {
    def x = new X()
    return x.a
  }
}

y = new Y()
println y.f()
```
runs throws a `[Static type checking] - No such property: a for class: X`.

```groovy
class X extends HashMap {
  def get(s) {
    return 7
  }
}

class Y {
  def f() {
    def x = new X()
    return x.a
  }
}

y = new Y()
println y.f()
```
runs fine, and prints `7`.

**Comment by notthetup** [comment]
Interesting. So I suggest either 

1. documenting that the example in https://github.com/org-arl/fjage-sentuator/blob/master/README.md doesn't work with [@CompileStatic](https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html) 
2. implementing the `Map` interface on `GenericMeasurement` so that the example will work with [@CompileStatic](https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html)

**Comment by mchitre** [comment]
Let's do the second. It'll make it uniform and simple across dynamic and static versions.
