### ISSUE TITLE
Publish the library as a Github package?

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage-sentuator#8]
Would it be possible to publish this library as a Github package so that it can be picked up as a dependency?

**Comment by mchitre** [comment]
Or Maven central, like we do for fjåge and fjåge-sentuator? Preference?

**Comment by notthetup** [comment]
No strict preference. My understanding is that Github is simpler than Maven, but I don't have much experience with either.

**Comment by notthetup** [comment]
OK. I missed the fact that it's already published. https://mvnrepository.com/artifact/com.github.org-arl/fjage-sentuator
